### ISSUE TITLE
Making codeblocks-dark.vim Pathogen-compatible

### ISSUE THREAD

**Issue by losgann** [noscript/codeblocks-dark.vim#1]
Moving "codeblocks-dark.vim" to a "colors " subdirectory will make this project pathogen-compatible. I cloned this project to my user\.vim\bundle\ subdirectory, moved codeblocks-dark.vim to ~\colors\  and it worked. See https://github.com/AlessandroYorba/Despacio for example.

**Comment by noscript** [comment]
Done! Thanks for example.

**Comment by losgann** [comment]
Thanks for you quick attention. Glad I could help (in a very small way)!
